# fill_y_first_addr_part2.py
import pandas as pd
import re
from pathlib import Path

# === IO ===
IN_PATH = Path("yandex_izmir_allrows_part2only.csv")
OUT_PATH = Path("../yandex_izmir_allrows_part2only_filled.csv")
UNFILLED_REPORT = Path("../unfilled_key_frequencies.csv")  # optional report

# === Your mapping ===
add_ilce = {
    "Havalimanı Şoşesi Harmandalı Meydanı": "Çiğli",
    "Akçay Caddesi Serbest Bölge Alt Geçit Öncesi": "Gaziemir",
    "Nursultan Nazarbayev Caddesi Adnan Kahveci Köprü Üstü": "Bayraklı",
    "Çevik Bir Meydanı Kavşak İçi": "Buca",
    "Halil Rıfat Paşa Caddesi Bahribaba Otobüs Durakları": "Karşıyaka",
    "Yeşildere Caddesi Mobilya Mağazası Önü": "Konak",
    "Halil Rıfat Paşa Caddesi Eshot Durakları": "Karşıyaka",
    "Gaziler Caddesi Tepecik Köprü Sonrası": "Konak",
    "Akçay Caddesi Serbest Bölge Alt Geçit": "Gaziemir",
    "Altınyol Caddesi Emniyet Müdürlüğü Otopark Hizası": "Bayraklı",
    "Anadolu Caddesi Çiğli İtfaiye Öncesi": "Çiğli",
    "Yeşildere Caddesi Mobilya Mağazası Hizası": "Konak",
    "Altınyol Caddesi Zafer Payzın Meles Katılımı": "Konak",
    "Özmen Caddesi Kadın Doğum Hastanesi": "Buca",
    "Akçay Caddesi Çevreyolu Katılımı Sonrası": "Gaziemir",
    "Ankara Caddesi Tepecik Hastane Önü": "Konak",
    "Altınyol Caddesi Zafer Payzın Öncesi": "Konak",
    "Yeşildere Caddesi Mobilya Mağazası Sonu": "Konak",
    "Yeşildere Caddesi Mobilya Mağazası Hizas": "Konak",
    "Yeşildere Caddesi Mobilya Mağaza Önü": "Konak",
    "Mürselpaşa Bulvarı Özel Hastane Hizası": "Konak",
    "Ankara Caddesi Osman Kibar Tüneli Ege Üniversitesi Girişi": "Bornova",
    "Akçay Caddesi Serbest Bölge Alt Geçit İçi": "Gaziemir",
    "Akçay Caddesi Serbest Bölge alt Geçit İçi": "Gaziemir",
    "Akçay Caddesi Serbest bölge Alt Geçit İçi": "Gaziemir",
    "Akçay Caddesi Serbest Bölge Alt Geçit Hizası": "Gaziemir",
    "Akçay Caddesi serbest Bölge Alt Geçit İçi": "Gaziemir",
    "Akçay Caddesi Serbest Bölge Sonrası": "Gaziemir",
    "Akçay Caddesi Serbest Bölge Çıkışı": "Gaziemir",
    "Akçay Caddesi Semt garajı Hizası": "Gaziemir",
    "Akçay Caddesi Serbest Bölge Altgeçit Girişi": "Gaziemir",
    "Akçay Caddesi Serbest Bölge Alt Geçit Hizası": "Gaziemir",
    "Akçay Caddesi Serbest Bölge Hizası": "Gaziemir",
    "Akçay Caddesi Serbest Bölge Öncesi": "Gaziemir",
    "Serbest Bölge Kavşağı Bölge Çıkışı": "Gaziemir",
    "Akçay Caddesi Serbest Bölge Alt Girişi": "Gaziemir",
    "Akçay Caddesi Serbest Bölge Alt Geçir Öncesi": "Gaziemir",
    "Akçay Caddesi Serbest Bölge Alt Geçit İçÖncesi": "Gaziemir",
    "Akçay Caddesi Serbest Bölge Yan Yolu": "Gaziemir",
    "Ankara Caddesi Ege Üniversitesi Viyadük Üstü": "Bornova",
    "Akçay Caddesi Semt Garajı Hizası": "Gaziemir",
    "Akçay Caddesi Serbest Bölge Alt Geçit Sonrası": "Gaziemir",
    "Yeşildere Caddesi Mobilya Mağazası Sonrası": "Konak",
    "Anadolu Caddesi Çiğli İtfaiye Hizası": "Çiğli",
    "Akçay Caddesi Gaziemir Alt Geçit Sonrası": "Gaziemir",
    "Yeşildere Caddesi Mobilya Mağazası Öncesi": "Konak",
    "Akçay Caddesi Sarnıç Alt Geçit Sonrası": "Konak",
    "Akçay Caddesi Serbest Bölge Alt Geçit Girişi": "Gaziemir",
    "Akçay Caddesi Serbest Bölge Alt Geçit Çıkışı": "Gaziemir",
    "Akçay Caddesi Serbest Bölge Kavşak İçi": "Gaziemir",
    "Anadolu Caddesi Turan Üst Geçit Sonrası": "Bayraklı",
    "Anadolu Caddesi Turan Otobüs Durakları Sonrası": "Bayraklı",
    "Anadolu Caddesi Turan Otobüs Durakları Hizası": "Bayraklı",
    "Anadolu Caddesi Turan Otobüs Durakları Öncesi": "Bayraklı",
    "Yeşillik Caddesi Semt Garajı Hizası": "Gaziemir",
    "Altınyol Caddesi Zafer Payzın Sonrası": "Konak",
    "Altınyol Caddesi Turan Köprü Üstü": "Bayraklı",
    "Caher Dudayev Bulvarı Yapı Market Hizası": "Karşıyaka",
    "Anadolu Caddesi Turan Köprü Sonrası": "Bayraklı",
    "Anadolu Caddesi Turan Köprü Öncesi": "Bayraklı",
    "Anadolu Caddesi Turan Üst Geçit Hizası": "Bayraklı",
    "Altınyol Caddesi Turan Köprü Öncesi": "Bayraklı",
    "Anadolu Caddesi Turan Üst Geçit Hizası": "Bayraklı",
    "Altınyol Caddesi Turan Köprü Öncesi": "Bayraklı",
    "Altınyol Caddesi Turan Otobüs Durakları Hizası": "Bayraklı",
    "Altınyol Caddesi Turan Otobüs Durakları Öncesi": "Bayraklı",
    "Altınyol Caddesi Turan Köprü Sonrası": "Bayraklı",
    "Altınyol Caddesi Turan Otobüs Durakları Sonrası": "Bayraklı",
    "Anadolu Caddesi Turan Üst Geçit Sonrası İlave Şeritte": "Bayraklı",
    "Anadolu Caddesi Turan otobüs Durakları Sonrası": "Bayraklı",
    "Anadolu Caddesi Turan Köprü Hizası": "Bayraklı",
    "Anadolu Caddesi Turan otobüs durakları öncesi": "Bayraklı",
    "Anadolu Caddesi Turan Otobüs Durağı Öncesi": "Bayraklı",
    "Anadolu Caddesi Turan Otobüs Durağı Sonrası": "Bayraklı",
    "Altınyol Caddesi Turan İzban Hizası": "Bayraklı",
    "Anadolu Caddesi Turan Otobüs Duraklar Sonrası": "Bayraklı",
    "Anadolu Caddesi Turan Otobüs Duraklar Hizası": "Bayraklı",
    "Altınyol Caddesi Turan Otobüs Durakları": "Bayraklı",
    "Ankara Caddesi Zafer Payzın Öncesi": "Konak",
    "Altınyol Caddesi Zafer Payzın Katılımı Sonrası": "Konak",
    "Altınyol Caddesi Zafer Payzın Katılımı": "Konak",
    "Altınyol Caddesi Zafer Payzın Katılımı Öncesi": "Konak",
    "Altınyol Caddesi Zafer Payzın Katılım": "Konak",
    "Ankara Caddesi Zafer Payzın Girişi": "Konak",
    "Ankara Caddesi Zafer Payzın İnişi": "Konak",
    "Ankara Caddesi Zafer Payzın Sonrası": "Konak",
    "Altınyol Caddesi Zafer Payzın Katılım Öncesi": "Konak",
    "Altınyol Caddesi Zafer Payzın İlave Şerit": "Konak",
    "Ankara Caddesi Zafer Payzın Katılımı": "Konak",
    "Liman Caddesi Zafer Payzın Katılımı": "Konak",
    "Anadolu Caddesi Zafer Payzın Öncesi": "Konak",
    "Ankara Caddesi Zafer Payzın Katılımı Sonrası": "Konak",
    "Ankara Caddesi Zafer Payzın Meles Katılım": "Konak",
    "Zafer Payzın Kavşağı Yol Ayrımı": "Konak",
    "Ankara Caddesi Zafer Payzın Katılım": "Konak",
    "Gaziler Caddesi Basmane Gar Hizası": "Konak",
    "Yeşillik Caddesi Yaşayanlar Kavşağı Sonrası": "Karabağlar",
    "Altınyol Caddesi İlave Şerit Başlangıç Noktası": "Konak",
    "Ankara Caddesi Çevreyolu Ayrımı Öncesi": "Bornova",
    "Ankara Caddesi Bölge Metro Öncesi": "Bornova",
    "Ankara Caddesi Bölge Metro Üst Geçit Sonrası": "Bornova",
    "Girne Bulvarı Özel Hastane Hizası": "Karşıyaka",
    "Yeşildere Caddesi Mobilya Mağaza Hizas": "Konak",
    "Gaziler Caddesi Kemer Alt Geçit Sonrası": "Konak",
    "Eşrefpaşa Caddesi Çankaya Katlı Otopark Hizası": "Konak",
    "Sarnıç Atatürk Caddesi Sarnıç Köprü Sonrası": "Gaziemir",
    "Mürselpaşa Bulvarı Özel Hastane Sonrası": "Konak",
    "Anadolu Caddesi İlave Şerit Başlangıç Noktası": "Konak",
    "Liman Caddesi Liman C Kapısı Hizası": "Konak",
    "Yeşildere Caddesi Özel Hastane Hizası": "Konak",
    "Caher Dudayev Bulvarı AVM Hizası": "Karşıyaka",
    "Anadolu Caddesi Çiğli Alt Geçit Sonrası": "Çiğli",
    "Eşrefpaşa Caddesi Agora Ören Yeri Hizası": "Konak",
    "Anadolu Caddesi Ayyıldız Kavşağı Sonrası": "Karşıyaka",
    "Ankara Caddesi Bölge Trafik Sonrası": "Bornova",
    "Ankara Caddesi Ege Üniversitesi Yol Ayrımı": "Bornova",
    "Anadolu Caddesi Çok Katlı Pazaryeri Hizası": "Karşıyaka",
    "Birleşmiş Milletler Caddesi Varyant İnişi": "Konak",
    "Üniversite Caddesi Ege Üniversitesi Kavşağı Öncesi": "Bornova",
    "Atatürk Caddesi Tekel Meydanı": "Konak",
    "Gaziler Caddesi Kemer Alt Geçit Öncesi": "Konak",
    "Akçay Caddesi Semt Garajı Öncesi": "Gaziemir",
    "Mürselpaşa Bulvarı Şehit Er Altan Yenil Üst Geçit Sonrası": "Konak",
    "Mustafa Kemal Sahil Bulvarı Depo Kavşağı Sonrası": "Konak",
    "Anadolu Caddesi İtfaiye Kavşak İçi": "Çiğli",
    "Ankara Caddesi Ege Üniversitesi Ayrımı": "Bornova",
    "Halil Rıfat Paşa Caddesi Konak Viyadük Altı": "Konak",
    "Halil Rıfat Paşa Caddesi Varyant İnişi": "Konak",
    "Anadolu Caddesi İlave Şerit Bitiş Noktası": "Karşıyaka",
    "Doğuş Caddesi Kız Yurdu Hizası": "Buca",
    "Mürselpaşa Bulvarı Özel Hastane Öncesi": "Konak",
    "Altınyol Caddesi Meles DGM Katılımı Sonrası": "Konak",
    "Altınyol Caddesi Meles Liman Yol Ayrımı Öncesi": "Konak",
    "Nursultan Nazarbayev Caddesi Smyrna Kavşak İçi": "Konak",
    "Birleşmiş Milletler Caddesi Varyant Girişi": "Konak",
    "Anadolu Caddesi Soğukkuyu Üst Geçit Hizası": "Bayraklı",
    "Gaziler Caddesi Basmane Kavşak İçi": "Konak",
    "Eşrefpaşa Caddesi Agora Ören Yeri Sonrası": "Konak",
    "Eşrefpaşa Caddesi AVM Hizası": "Konak",
    "Gaziler Caddesi Basmane Kavşağı Sonrası": "Konak",
    "Ankara Caddesi Ege Üniversitesi Yol Ayrımı Öncesi": "Bornova",
    "Cumhuriyet Bulvarı Borsa Hizası": "Konak",
    "Menderes Caddesi Buca Belediyesi Sonrası": "Buca",
    "Birleşmiş Milletler Caddesi Fatih Cami Hizası": "Konak",
    "Mithatpaşa Caddesi Eşref Bitlis Alt Geçit Sonrası": "Balçova",
    "İnönü Caddesi Nokta Durağı Hizası": "Karabağlar",
    "Anadolu Caddesi Naldöken Yaya Üst Geçit Hizası": "Bayraklı",
    "Ankara Caddesi Ege Üniversitesi Viyadük Üzeri": "Bornova",
    "Anadolu Caddesi Katlı Pazaryeri Sonrası": "Karşıyaka",
    "İnönü Caddesi Göztepe Metro Öncesi": "Konak",
    "Mürselpaşa Bulvarı Mobilya Mağazası Öncesi": "Konak",
    "Anadolu Caddesi İtfaiye Hizası": "Çiğli",
    "Halide Edip Adıvar Caddesi Metro İnşaatı Hizası": "Konak",
    "Anadolu Caddesi İzmir Arena Hizası": "Bayraklı",
    "Gaziler Caddesi Gıda Çarşısı Girişi": "Konak",
    "Şair Eşref Bulvarı Montrö Meydanı Kavşak İçi": "Konak",
    "Caher Dudayev Bulvarı Yapı Market Önü": "Karşıyaka",
    "Gaziler Caddesi Gıda Çarşısı Kavşağı": "Konak",
    "Anadolu Caddesi Ayyıldız Durakları Hizası": "Karşıyaka",
    "Girne Bulvarı Girne Pazaryeri Öncesi": "Karşyaka",
    "Anadolu Caddesi Çiğli İtfaiye Kavşağı": "Çiğli",
    "Anadolu Caddesi İtfaiye Kavşağı": "Çiğli",
    "Ankara Caddesi Çevreyolu Ayrımı Sonrası": "Bornova",
    "Ankara Caddesi Türkan Özilhan Hastanesi Hizası": "Bornova",
    "Talatpaşa Bulvarı Tekel Meydanı Öncesi": "Konak",
    "Akçay Caddesi Gaziemir Alt Geçit sonrası": "Gaziemir",
    "Gaziosmanpaşa Bulvarı Çankaya Katlı Otopark Hizası": "Konak",
    "Yeşildere Caddesi Mobilya Magazası Önü": "Konak",
    "Akçay Caddesi Semt Garajı Lambalar": "Gaziemir",
    "Liman Caddesi Liman D Kapısı Hizası": "Konak",
    "Liman Caddesi Alsancak Gar Sonrası": "Konak",
    "Kemalpaşa Caddesi BMC Kavşağı Sonrası": "Bornova",
    "Ankara Caddesi Bornova Metro Hizası": "Bornova",
    "Eşrefpaşa Caddesi Agora Ören Yeri Öncesi": "Konak",
    "Yeşildere Caddesi Buca Katılımı Sonrası": "Buca",
    "Akçay Caddesi Optimum Kavşağı": "Gaziemir",
    "Akçay Caddesi Havalimanı Kavşağı Sonrası": "Gaziemir",
    "Anadolu Caddesi Çiğli İtfaiye Kavşağı Öncesi": "Çiğli",
    "Hasan Ali Yücel Bulvarı Bostanlı İskele Öncesi": "Karşıyaka",
    "Altınyol Caddesi DGM Köprü Öncesi Liman Yol Ayrımı Hizası": "Konak",
    "Altınyol Caddesi Benzinlik Hizası": "Konak",
    "Altınyol Caddesi Sahil Güvenlik Hizası": "Konak",
    "Nursultan Nazarbayev Caddesi Altınyol Bağlantı Noktası": "Konak",
    "Altınyol Caddesi İlave Şerit Çıkışı": "Karşıyaka",
    "Altınyol Caddesi Ek Şerit Başlangıç Noktası": "Konak",
    "Altınyol Caddesi İlave Şerit Başlangıç": "Konak",
    "Altınyol Caddesi İlave Şerit Bitiş Noktası": "Karşıyaka",
    "Mithatpaşa Caddesi Eşref Bitli Alt Geçit Sonrası": "Balçova",
    "Anadolu Caddesi Naldöken Benzinlik Öncesi": "Bayraklı",
    "Nursultan Nazarbayev Caddesi Adnan Kahveci Köprü Öncesi": "Bayraklı",
    "Anadolu Caddesi Naldöken Köprü Öncesi Benzinlik Hizası": "Bayraklı",
    "Anadolu Caddesi Naldöken Köprü Benzinlik Öncesi": "Bayraklı",
    "Anadolu Caddesi Naldöken Üst Geçit Hizası": "Bayraklı",
    "Nursultan Nazarbayev Caddesi Naldöken Köprü Üstü": "Bayraklı",
    "Ankara Caddesi Ege Üniversitesi Viyadük Öncesi": "Bornova",
    "Ankara Caddesi Ege Üniversitesi Yol Ayrımı Hizası": "Bornova",
    "Pınar Caddesi BMC Kavşağı Sonrası": "Bornova",
    "Ankara Caddesi Ege Üniversitesi Kavşağı Öncesi": "Bornova",
    "Üniversite Caddesi Ege Üniversitesi Viyadük Üstü": "Bornova",
    "Yeşildere Caddesi Ege Üniversitesi Viyadük Üstü": "Bornova",
    "Akçay Caddesi Semt Garajı Karşısı": "Gaziemir",
    "Menderes İzmir Aydın Yolu Havalimanı Kavşağı": "Gaziemir",
    "Menderes Caddesi Havalimanı Kavşak İçi": "Gaziemir",
    "Akçay Caddesi Semt Garajı Sonrası": "Gaziemir",
    "Anadolu Caddesi Bostanlı İskele Hizası": "Karşıyaka",
    "Girne Bulvarı Çevreyolu Katılımı": "Karşıyaka",
    "Caher Dudayev Bulvarı Tramvay Durağı Önü": "Karşıyaka",
    "Girne Bulvarı Özel Hastane Işıklar": "Karşıyaka",
    "Caher Dudayev Bulvarı Alışveriş Merkezi Önü": "Karşıyaka",
    "Anadolu Caddesi Çok Katlı Pazaryeri Sonrası": "Karşıyaka",
    "Girne Bulvarı Girne Lunapark Öncesi": "Karşıyaka",
    "Anadolu Caddesi Ek Şerit Bitiş Noktası": "Karşıyaka",
    "Girne Bulvarı ÖZel Hastane Hizası": "Karşıyaka",
    "Girne Bulvarı 1751 Sokak Kesişimi": "Karşıyaka",
    "Girne Bulvarı Altınyol Ayrımı": "Karşıyaka",
    "Girne Bulvarı Girne Kültürpark Öncesi": "Karşıyaka",
    "Caher Dudayev Bulvarı Alışveriş Merkezi Hizası": "Karşıyaka",
    "Girne Bulvarı 80. yıl Cumhuriyet Parkı Sonrası": "Karşıyaka",
    "Girne Bulvarı Karşıyaka Atatürk Anıtı Hizası": "Karşıyaka",
    "Caher Dudayev Bulvarı Benzinlik Hizası": "Karşıyaka",
    "Caher Dudayev Bulvarı Yapı Market Öncesi": "Karşıyaka",
    "Girne Bulvarı Girne Pazaryeri Hizası": "Karşıyaka",
    "Girne Bulvarı Yunuslar Hizası": "Karşıyaka",
    "Girne Bulvarı Özel Hastane Kavşağı Öncesi": "Karşıyaka",
    "Caher Dudayev Bulvarı Atakent Tramvay Durağı Hizası": "Karşıyaka",
    "Anadolu Caddesi Çiğli İtfaiye Kavşak İçi": "Karşıyaka",
    "Yeni Girne Bulvarı Özel Hastane Hizası": "Karşıyaka",
    "Girne Bulvarı Kareksan Hizası": "Karşıyaka",
    "Caher Dudayev Bulvarı Mavişehir AVM Hizası": "Karşıyaka",
    "Caher Dudayev Bulvarı Tramvay Durağı Hizası": "Karşıyaka",
    "Gaziler Caddesi Mezarlıklar Müdürlüğü Hizası": "Konak",
    "Cumhuriyet Bulvarı Borsa Binası Önü": "Konak",
    "Mürselpaşa Bulvarı Şehit Er Altan Yenil Üst Geçit Öncesi": "Konak",
    "Anadolu Caddesi Ek Şerit Başlangıç Noktası": "Konak",
    "Anadolu Caddesi Meles Delta Hizası Liman Yol Ayrımı": "Konak",
    "Liman Caddesi Tariş Otobüs Durakları Hizası": "Konak",
    "Gaziler Caddesi Gıda Çarşı Kavşağı Sonrası": "Konak",
    "Mürselpaşa Bulvarı Özel Hastane Hizası Sonrası": "Konak",
    "Cumhuriyet Bulvarı Gümrük Kavşağı": "Konak",
    "Cumhuriyet Bulvarı Vergi Dairesi Hizası": "Konak",
    "Gaziler Caddesi Mezarlık Daire Başkanlığı Hizası": "Konak",
    "Liman Caddesi Tarihi Su Kemerleri Öncesi": "Konak",
    "Atatürk Caddesi Tekel Alsancak Gar Sonrası": "Konak",
    "Liman Caddesi Arkas Hizası": "Konak",
    "Gaziler Caddesi Tepecik Köprü Yan Yolu": "Konak",
    "Talatpaşa Bulvarı Tekel Meydanı": "Konak",
    "Gaziler Caddesi İtfaiye Sonrası": "Konak",
    "Birleşmiş Milletler Caddesi Fatih Camii Hizası": "Konak",
    "Gaziler Caddesi İtfaiye Kavşağı": "Konak",
    "Gaziosmanpaşa Bulvarı Katlı Otopark Hizası": "Konak",
    "Şair Eşref Bulvarı Tekel Meydanı Öncesi": "Konak",
    "Gaziler Caddesi Ağırbakım Fabrikası Hizası": "Konak",
    "Eşrefpaşa Caddesi Özel AVM Hizası": "Konak",
    "Gaziler Caddesi Eşrefpaşa Hastanesi Kavşağı Sonrası": "Konak",
    "Gaziler Caddesi Gıda Çarşısı Kavşak İçi": "Konak",
    "Gaziler Caddesi Ağır Bakım Hizası": "Konak",
    "Eşrefpaşa Caddesi Agora Ören Sonrası": "Konak",
    "Gaziler Caddesi Gıda Çarşısı Hizası": "Konak",
    "Yeşildere Caddesi Mabilya Mağazası Hizası": "Konak",
    "Cumhuriyet Bulvarı Borsa Kavşağı Sonrası": "Konak",
    "Cumhuriyet Bulvarı Eski Borsa Binası Hizası": "Konak",
    "Gaziler Caddesi Basmane Gar hizası": "Konak",
    "Cumhuriyet Bulvarı Ticaret Odası Hizası": "Konak",
    "Atatürk Caddesi Tekel Meydanı Öncesi": "Konak",
    "Eşrefpaşa Caddesi Agora Örenyeri Sonrası": "Konak",
    "Liman Caddesi Alsancak Tramvay Hizası": "Konak",
    "Gaziler Caddesi Kapı Kavşak İçi": "Konak",
    "Gaziler Caddesi Kapılar Kavşak İçi": "Konak",
    "Gaziler Caddesi İtfaiye Işıklar Öncesi": "Konak",
    "Gaziler Caddesi Kapılar Benzinlik Hizası": "Konak",
    "Anadolu Caddesi İtfaiye Kavşağı Öncesi": "Çiğli",
    "Anadolu Caddesi Soğukkuyu Üst Geçit Öncesi": "Bayraklı",
    "Anadolu Caddesi Soğukkuyu Yeni Girne Yol Ayrımı": "Bayraklı",
    "Anadolu Caddesi Soğukkuyu Cami Hizası": "Bayraklı",
    "Anadolu Caddesi Soğukkuyu Yaya Üst Geçit Sonrası": "Bayraklı",
    "Anadolu Caddesi Soğukkuyu Üst Geçit Sonrası": "Bayraklı",
    "Kemalpaşa Caddesi Efes Pilsen Hizası": "Bornova",
    "Kemalpaşa Caddesi Otogar Kavşağı Sonrası": "Bornova",
    "Kemalpaşa Caddesi Otogar Köprü Altı": "Bornova",
    "Akçay Caddesi Çevreyolu Bağlantı Sonrası": "Gaziemir",
    "Akçay Caddesi Alt Geçit Çıkış Sonrası": "Gaziemir",
    "Akçay Caddesi Gaziemir Alt Geçit Öc": "Gaziemir",
    "Akçay Caddesi Gaziemir Alt Geçit Öm": "Gaziemir",
    "Yeşillik Caddesi Yaşayanlar Kavşağı Yan Yol": "Karabağlar",
    "Yeni Girne Caddesi Özel Hastane Kavşağı": "Karşıyaka",
    "Yeşildere Caddesi Özel Hastane Sonrası": "Konak",
    "Birleşmiş Milletler Caddesi Kız Öğrenci Yurdu Öncesi": "Konak",
    "Mürselpaşa Bulvarı Hilal Köprü Sonrası": "Konak",
    "Şair Eşref Bulvarı Fuar Öncesi": "Konak",
    "Yeşildere Caddesi Hastane Önü": "Konak",
    "Şair Eşref Bulvarı Lozan Meydan Öncesi": "Konak",
    "Yeşildere Caddesi Halide Edip Adıvar Katılımında": "Konak",
    "Yeşildere Caddesi Besaş Otobüs Durakları Sonrası": "Konak",
    "Şair Eşref Bulvarı İtfaiye Kavşağı Öncesi": "Konak",
    "Mürselpaşa Bulvarı Basmane Yık Ayrımı": "Konak",
    "Birleşmiş Milletler Caddesi Varyant Sonrası": "Konak",
    "Birleşmiş Milletler Caddesi Kız Öğrenci Yurdu Hizası": "Konak",
    "Birleşmiş Milletler Caddesi Çocuk Müzesi Hizası": "Konak",
    "Mürselpaşa Bulvarı Meslek Fabrikası Öncesi": "Konak",
    "Şair Eşref Bulvarı Lozan Meydanı Öncesi": "Konak",
    "Birleşmiş Milletler Caddesi Oyuncak Müzesi Hizası": "Konak",
    "Anadolu Caddesi Çiğli Belediye Sonrası": "Çiğli",
    "Ankara Caddesi Çiğli İtfaiye Hizası": "Çiğli",
    "Anadolu Caddesi Çiğli Emine Sultan Cami Öncesi": "Çiğli",
    "Anadolu Caddesi Çiğli İtfaiye Kavşak içi": "Çiğli",
    "Anadolu Caddesi İtfaiye Sonrası": "Çiğli",
    "Mithatpaşa Caddesi İstinye Park Önü": "Karabağlar",
    "Anadolu Caddesi Liman Ayrımı Öncesi": "Konak",
    "Gaziemir Altgeçit Çıkışı Hilal Köprü Üstü": "Konak",
    "Mithatpaşa Caddesi Yapı Market Hizası": "Balçova",
    "Smyrna Meydanı Smyrna Kavşağı": "Konak",
    "Hasan Güven Caddesi Uğur Okulları Hizası": "Gaziemir",
    "Anadolu Caddesi İtfaiye Önü": "Çiğli",
    "Anadolu Caddesi İtfaiye Işıklar Öncesi": "Çiğli",
    "Yeşillik Caddesi Paşa Köprü Lambalar Sonrası": "Karabağlar",
    "Ankara Caddesi Bayraklı Tapu Müdürlüğü Önü": "Bayrakli",
    "Halide Edip Adıvar Caddesi Yeşillik Caddesi Katılımı Kavşak İçi": "Karabağlar",
    "Doğuş Caddesi Tınaztepe Hastane Kavşağı": "Buca",
    "Yeşillik Caddesi Konak Belediyesi Öncesi": "Karabağlar",
    "Uğur Mumcu Caddesi Buca Heykel Öncesi": "Buca",
    "Atatürk Caddesi Buca Mezarlığı Hizası": "Buca",
    "Menderes Caddesi Şirinyer Tapu Hizası": "Buca",
    "Halil Rıfat Paşa Caddesi Konak Yaya Üst Geçit Altı": "Konak",
    "Yeşillik Caddesi Ptt Hizası": "Karabağlar",
    "Doğuş Caddesi 3. Sokak kesişimi": "Buca",
    "Yeşillik Caddesi PTT Hizası": "Karabağlar",
    "Anadolu Caddesi Şemikler Üst Geçit Öncesi": "Karşıyaka",
    "Anadolu Caddesi Şemikler Üst Geçit Sonrası": "Karşıyaka",
    "Anadolu Caddesi Şemikler Mezarlık Öncesi": "Karşıyaka",
    "Anadolu Caddesi Şemikler Lambalar": "Karşıyaka",
    "İstanbul Caddesi Topçu Tugayı Hizası": "Bornova",
    "İstanbul Caddesi Topçu Tugayı Karşısı": "Bornova",
    "Çevreyolu Fuar İzmir Hizası": "Gaziemir",
    "Gazi Bulvarı Borsa Kavşağı Öncesi": "Konak",
    "Gazi Bulvarı Borsa Otobüs Durakları Hizası": "Konak",
    "Cemal Gürsel Caddesi Nikah Sarayı Hizası": "Karşıyaka",
    "Cemal Gürsel Caddesi Nikah Sarayı Öncesi": "Karşıyaka",
    "Cemal Gürsel Caddesi Nikah Sarayı": "Karşıyaka",
    "Cemal Gürsel Caddesi Zübeyde Nikah Sarayı Hizası": "Karşıyaka",
    "Cemal Gürsel Caddesi Atatürk Anıtı Sonrası": "Karşıyaka",
    "Anadolu Caddesi Adnan Kahveci Öncesi": "Karşıyaka",
    "Aydınlar Caddesi Ayakkabıcılar Sitesi Otoban Girişi": "Bornova",
    "Yüzbaşı Hakkı İbrahim Caddesi Smyrna Meydanı Kavşak İçi": "Bornova",
    "Yüzbaşı İbrahim Hakkı Caddesi Çevreyolu Katılımı": "Bornova",
    "İnönü Caddesi Poligon Işıklar": "Karabağlar",
    "Şehitler Caddesi Halkapınar Aktarma Lambalar": "Konak",
    "Şehitler Caddesi Halkapınar Otobüs Durakları": "Konak",
    "Ozan Abay Caddesi Adliye Ayrımı": "Konak",
    "Kamil Tunca Caddesi Vakıflar Kavşağı Sonrası": "Bornova",
    "Kamil Tunca Caddesi Otogar Kavşak İçi": "Bornova",
    "Ozan Abay Caddesi AVM Hizası": "Konak",
    "Şehitler Caddesi Benzinlik Hizası": "Konak",
    "Şehitler Caddesi Benzinlik Kavşağı": "Konak",
    "Şehitler Caddesi Stadyum Hizası": "Konak",
    "Şehitler Caddesi Vakıfları Kavşağı Sonrası": "Konak",
    "Mustafa Kemal Sahil Bulvarı Göztepe Metro Hizası": "Konak",
    "Mustafa Kemal Sahil Bulvarı Köstence Tramvay Durağı Hizası": "Konak",
    "Ankara Caddesi Teknoloji Market Hizası": "Bornova",
    "Anadolu Caddesi Serinkuyu Jandarma Öncesi": "Bayraklı",
    "Anadolu Caddesi Ziraat Bankası Karşısı": "Karşıyaka",
    "Gaziosmanpaşa Bulvarı Çankaya Katlı Otopark Önü": "Konak",
    "Üniversite Caddesi Çevreyolu Katılım Sonrası": "Bornova",
    "Eşrefpaşa Caddesi Polis Merkez Öncesi": "Konak",
    "Anadolu Caddesi Harmandalı Alt Geçit Sonrası": "Çiğli",
    "Ankara Caddesi Trafik Hastanesi Kavşağı": "Bornova",
    "Manas Bulvarı Adliye Kavşağı": "Konak",
    "Eşrefpaşa Caddesi Şelale Parkı Benzin İstasyon Önü": "Konak",
    "Pakistan Bulvarı Benzinlik Hizası": "Konak",
    "Mithatpaşa Caddesi İstihkam Okulu Nizamiye Hizası": "Narlıdere",
    "Anadolu Caddesi Sahil Ayrımı": "Bayraklı",
    "Halil Rıfat Paşa Caddesi Arkeoloji ve Entonografya Müzesi Öncesi": "Konak",
    "Mustafa Kemal Caddesi Migros Kavşağı": "Bornova",
    "Gazi Bulvarı İtfaiye Kavşağı": "Konak",
    "Eşrefpaşa Caddesi İkiçeşmelik Özel Eğitim Merkezi Hizası": "Konak",
    "Gazi Bulvarı İtfaiye Sonrası": "Konak",
    "Anadolu Caddesi Sahil Güvenlik Hizası": "Bayraklı",
    "Şehit Er Mehmet Çadırcı Caddesi İtfaiye Hizası": "Buca",
    "Halide Edip Adıvar Caddesi Şelale Parkı Hizası": "Karabağlar",
    "Çevreyolu Narlıdere Kavşağı Öncesi": "Narlıdere",
    "Halil Rıfat Paşa Caddesi Varyanta Dönüş": "Konak",
    "Eşrefpaşa Caddesi Şelale Park Hizası": "Konak",
    "İnönü Caddesi Denizmen Metro Durağı Hizası": "Konak",
    "Mustafa Kemal Sahil Bulvarı Vergi Dairesi Hizası": "Konak",
    "Ay Sokak İstinye Park Alt Geçit Sonrası": "Balçova",
    "Önder Caddesi Migros Kavşağı": "Gaziemir",
    "Mithatpaşa Caddesi Ege Park Kavşağı Öncesi": "Balçova",
    "İnönü Caddesi Göztepe Stadı Hizası": "Konak",
    "Pakistan Bulvarı İzmirgaz Hizası": "Konak",
    "Atatürk Caddesi Kaynaklar Hal Kavşağı Sonrası": "Buca",
    "Çevreyolu Mavişehit Katılımı Öncesi": "Karşıyaka",
    "Pakistan Bulvarı Gıda Çarşısı Girişi": "Konak",
    "Anadolu Caddesi Hastane Kavşak İçi": "Karşıyaka",
    "Ankara Caddesi İzmir Emniyet Müd. Çevik Kuvvet Şb. Müd. Hizası": "Bornova",
    "Kıbrıs Caddesi Hasanağa Parkı Hizası": "Buca",
    "Anadolu Caddesi İlave Şerit Girişi": "Konak",
    "Atatürk Caddesi Hava Eğitim Komutanlığı Öncesi": "Çiğli",
    "Mustafa Kemal Sahil Bulvarı Tramvay Durağı Hizası": "Konak",
    "Ankara Caddesi Çevreyolu Katılı Öncesi": "Bornova",
    "Gürçeşme Caddesi Polis Okulu Öncesi": "Konak",
    "Süleyman Demirel Bulvarı Gaziemir Polis Kapama Noktası": "Gaziemir",
    "Akdoğan Caddesi Adli Tığ Hizası": "Buca",
    "Otoban Çıkışı Levent Marina Kavşak İçi": "Balçova",
    "Varyant Varyant İnişi": "Konak",
    "Ankara Caddesi Çevreyolu Bağlantı Öncesi": "Bornova",
    "İnönü Caddesi Denizmen Lambalar Öncesi": "Karabağlar",
    "Pakistan Bulvarı İzmir Gaz Hizası": "Konak",
    "İkiçeşmelik Caddesi Agora Kent Önü": "Konak",
    "Eşrefpaşa Caddesi Benzinlik Hizası": "Konak",
    "Atatürk Caddesi Kaynaklar Hal Girişi": "Buca",
    "Mithatpaşa Caddesi Polis Evi Hizası": "Konak",
    "Eşrefpaşa Caddesi Kestelli Lambalar Sonrası": "Konak",
    "Anadolu Caddesi Benzinlik Hizası": "Karşıyaka",
}

# === Read CSV (handle BOM if present) ===
try:
    df = pd.read_csv(IN_PATH, encoding="utf-8-sig")
except UnicodeDecodeError:
    df = pd.read_csv(IN_PATH)  # fallback

# === Columns ===
result_col = "y_first_addr_part2"  # (your file has underscore, not hyphen)

# Build CADDE + KONUM if present
cadde_konum_col = None
if {"CADDE", "KONUM"}.issubset(df.columns):
    cadde_konum_col = "_CADDE_PLUS_KONUM"
    df[cadde_konum_col] = (
            df["CADDE"].astype(str).str.strip() + " " + df["KONUM"].astype(str).str.strip()
    ).str.replace(r"\s+", " ", regex=True)

# Candidate key columns in order
candidates = [c for c in ["y_query", cadde_konum_col, "y_first_address", "y_first_name"] if c and c in df.columns]


# === Helper to grab the first usable key from the row ===
def first_key(row):
    for c in candidates:
        val = row[c]
        if pd.isna(val):
            continue
        key = str(val).strip()
        if key:
            return key
    return None


# === Fill only where missing/empty ===
is_empty = df[result_col].isna() | (df[result_col].astype(str).str.strip() == "")
before_missing = int(is_empty.sum())

# Collect the attempted keys for rows we try to fill (useful for reporting)
attempt_keys = []


def fill_value(row):
    if pd.isna(row[result_col]) or str(row[result_col]).strip() == "":
        key = first_key(row)
        attempt_keys.append(key)
        if key in add_ilce:
            return add_ilce[key]
    return row[result_col]


df.loc[is_empty, result_col] = df.loc[is_empty].apply(fill_value, axis=1)

# === Stats & save ===
after_missing = int((df[result_col].isna() | (df[result_col].astype(str).str.strip() == "")).sum())
filled_count = before_missing - after_missing

df.to_csv(OUT_PATH, index=False)

print(f"Candidates used (in order): {candidates}")
print(f"Missing before: {before_missing}")
print(f"Filled: {filled_count}")
print(f"Still missing: {after_missing}")
print(f"Saved: {OUT_PATH}")

# === Optional: report unfilled key frequencies so you can extend the dictionary ===
# (only for rows we attempted to fill but had no mapping)
if attempt_keys:
    # keep only those that didn't map
    unfilled_keys = [k for k in attempt_keys if (k is not None and k not in add_ilce)]
    print(unfilled_keys)
    if unfilled_keys:
        report = (
            pd.Series(unfilled_keys, name="key")
            .value_counts()
            .rename_axis("key")
            .reset_index(name="count")
        )
        report.to_csv(UNFILLED_REPORT, index=False)
        print(f"Unfilled key frequency report saved to: {UNFILLED_REPORT}")
